#!/bin/bash -e

ORG_PATH="github.com/nildev"
REPO_PATH="${ORG_PATH}/project"

echo "Building project"
CGO_ENABLED=0 godep go build -o bin/project -a -installsuffix netgo -ldflags '-s'
chmod +x bin/project